### PR TITLE
Fix default interpolation steps parsing

### PR DESCRIPTION
**Pull request by ljleb**

### CODE REVIEW

**Comment by John-WL** [comment]
can I merge this?

**Comment by ljleb** [comment]
> can I merge this?

not really, some of the code is a bit hacky still. I'll change this pr to draft to indicate its a wip

**Comment by John-WL** [comment]
yes, I agree with this

**Comment by ljleb** [comment]
> yes, I agree with this

If we remove them, it should be put in a different extension. I think we should keep them in util they are moved somewhere else.

**Pull request merged**
